export { DEFAULT_IGNORED_DIRECTORIES } from 'envanalyser-contracts';
export { createDefaultProjectDiscoveryDependencies, createProjectDiscoveryService } from './create-project-discovery-service.js';
export { DefaultProjectDiscoveryService } from './project-discovery-service.js';
export type { ProjectDiscoveryDependencies } from './project-discovery-service.js';
export type { FileSystemReader } from './interfaces/file-system-reader.js';
export type { ProjectDiscoveryService } from './interfaces/project-discovery-service.js';
export type { ProjectMarkerDetector } from './interfaces/project-marker-detector.js';
export type { WorkspaceManagerDetector } from './interfaces/workspace-manager-detector.js';
export { NodeFileSystemReader } from './filesystem/node-file-system-reader.js';
export { createDefaultProjectMarkerDetectors } from './project-markers/index.js';
export { createDefaultWorkspaceDetectors } from './workspace-detectors/index.js';
export { WorkspaceRootResolver } from './workspace-root-resolver.js';
