export const ISSUE_CODES = {
  ENV_DUPLICATE: 'ENV_DUPLICATE',
  ENV_EMPTY: 'ENV_EMPTY',
  ENV_MISSING: 'ENV_MISSING',
  ENV_OPTIONAL: 'ENV_OPTIONAL',
  ENV_UNCONFIGURED: 'ENV_UNCONFIGURED',
  ENV_UNUSED: 'ENV_UNUSED',
} as const;
